apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-billing-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-billing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-billing
  template:
    metadata:
      labels:
        app: mysql-billing
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "billing_db"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "password"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-billing-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-billing-storage
          persistentVolumeClaim:
            claimName: mysql-billing-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-billing
spec:
  selector:
    app: mysql-billing
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
