apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS order_db;
    CREATE DATABASE IF NOT EXISTS inventory_db;
    CREATE DATABASE IF NOT EXISTS customer_db;
    CREATE DATABASE IF NOT EXISTS billing_db;
    CREATE DATABASE IF NOT EXISTS payment_db;