spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://stock-web-app:4200"         # Pour Angular dans le conteneur
              - "http://stock-web-app-react:4300"   # Pour React dans le conteneur
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowCredentials: true
