name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer JDK 17 pour compiler les microservices Spring Boot
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3️⃣ Compiler chaque microservice avec Maven
      - name: Build microservices with Maven
        run: |
          SERVICES=("eureka-registry-service" "config-service" "api-gateway-service" "customer-service" "inventory-service" "order-service" "billing-service" "payment-service")
          
          for SERVICE in "${SERVICES[@]}"; do
            echo "🔹 Compilation de $SERVICE"
            mvn -f $SERVICE/pom.xml clean install -DskipTests
          done

      # 4️⃣ Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Builder et Pousser les images Docker sur Docker Hub
      - name: Build and Push Docker Images
        run: |
          DOCKER_HUB_USERNAME=ton-dockerhub
          
          SERVICES=("eureka-registry-service" "config-service" "api-gateway-service" "customer-service" "inventory-service" "order-service" "billing-service" "payment-service" "stock-web-app")

          for SERVICE in "${SERVICES[@]}"; do
            IMAGE_NAME="$DOCKER_HUB_USERNAME/$SERVICE:latest"
          
            echo "🔹 Build de l'image $IMAGE_NAME"
            docker build -t $IMAGE_NAME ./$SERVICE

            echo "📤 Push de l'image $IMAGE_NAME"
            docker push $IMAGE_NAME
          done
