name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer JDK 17 pour compiler les microservices Spring Boot
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3️⃣ Ajouter le cache Maven pour les dépendances
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Installer base-domaine-service (pour que les autres services puissent en dépendre)
      - name: Install base-domaine-service
        run: |
          echo "🔹 Installation de base-domaine-service"
          mvn -f base-domaine-service/pom.xml clean install -DskipTests

      # 5️⃣ Compiler chaque microservice avec Maven
      - name: Build microservices with Maven
        run: |
          SERVICES=("base-domaine-service" "eureka-registry-service" "config-service" "api-ga
