name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Déclenche le workflow quand on push sur la branche main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Images
        env:
          IMAGE_TAG: latest  # Change si nécessaire
        run: |
          services=(eureka-registry-service config-service api-gateway-service customer-service inventory-service order-service billing-service payment-service)

          for service in "${services[@]}"; do
            echo "Building and pushing image for $service"
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:$IMAGE_TAG ./$service
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:$IMAGE_TAG
          done
